# Generated by Django 6.0.4 on 2026-05-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participatie', '0002_alter_proposal_options_proposal_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
