# Generated by Django 6.0.4 on 2026-05-09 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participatie', '0005_rename_votes_to_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-likes', '-created_at']},
        ),
    ]
