# Generated by Django 6.0.4 on 2026-05-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participatie', '0006_alter_proposal_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-votes', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='likes',
        ),
        migrations.AddField(
            model_name='proposal',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
