# Generated by Django 6.0.4 on 2026-05-12 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participatie', '0007_alter_proposal_options_remove_proposal_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveupdate',
            name='status',
            field=models.CharField(choices=[('gesprek', 'In gesprek'), ('raad', 'In de raad'), ('behandeling', 'In behandeling')], default='gesprek', max_length=20),
        ),
    ]
