# Generated by Django 6.0.4 on 2026-05-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participatie', '0004_liveupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='votes',
            new_name='likes',
        ),
    ]
