# Generated by Django 6.0.4 on 2026-05-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participatie', '0007_alter_proposal_options_remove_proposal_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='votes_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proposal',
            name='votes_for',
            field=models.IntegerField(default=0),
        ),
    ]
