# Generated by Django 6.0.4 on 2026-05-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participatie', '0008_proposal_votes_against_proposal_votes_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='theme',
            field=models.CharField(choices=[('veiligheid', 'Veiligheid'), ('verkeer', 'Verkeer & Mobiliteit'), ('groen', 'Groen & Duurzaamheid'), ('wonen', 'Wonen'), ('onderwijs', 'Onderwijs & Jeugd'), ('zorg', 'Zorg & Welzijn'), ('cultuur', 'Cultuur & Sport'), ('overig', 'Overig')], default='overig', max_length=50),
        ),
    ]
